/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as GameRouteImport } from './routes/_game'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTestRouteImport } from './routes/_layout/test'
import { Route as GamesDartUiRouteImport } from './routes/_games/dartUi'
import { Route as GamesDartRouteImport } from './routes/_games/dart'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/_game',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTestRoute = LayoutTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => LayoutRoute,
} as any)
const GamesDartUiRoute = GamesDartUiRouteImport.update({
  id: '/_games/dartUi',
  path: '/dartUi',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDartRoute = GamesDartRouteImport.update({
  id: '/_games/dart',
  path: '/dart',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dart': typeof GamesDartRoute
  '/dartUi': typeof GamesDartUiRoute
  '/test': typeof LayoutTestRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dart': typeof GamesDartRoute
  '/dartUi': typeof GamesDartUiRoute
  '/test': typeof LayoutTestRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_game': typeof GameRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_games/dart': typeof GamesDartRoute
  '/_games/dartUi': typeof GamesDartUiRoute
  '/_layout/test': typeof LayoutTestRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/signup' | '/dart' | '/dartUi' | '/test' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/signup' | '/dart' | '/dartUi' | '/test' | '/'
  id:
    | '__root__'
    | '/_game'
    | '/_layout'
    | '/login'
    | '/signup'
    | '/_games/dart'
    | '/_games/dartUi'
    | '/_layout/test'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GameRoute: typeof GameRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  GamesDartRoute: typeof GamesDartRoute
  GamesDartUiRoute: typeof GamesDartUiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_game': {
      id: '/_game'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/test': {
      id: '/_layout/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof LayoutTestRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_games/dartUi': {
      id: '/_games/dartUi'
      path: '/dartUi'
      fullPath: '/dartUi'
      preLoaderRoute: typeof GamesDartUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_games/dart': {
      id: '/_games/dart'
      path: '/dart'
      fullPath: '/dart'
      preLoaderRoute: typeof GamesDartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutTestRoute: typeof LayoutTestRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutTestRoute: LayoutTestRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GameRoute: GameRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  GamesDartRoute: GamesDartRoute,
  GamesDartUiRoute: GamesDartUiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
